steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/hostinte/cloud-run-source-deploy/tictactoe:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/hostinte/cloud-run-source-deploy/tictactoe:latest',
      ]

images:
  - us-central1-docker.pkg.dev/hostinte/cloud-run-source-deploy/tictactoe:latest
